"""rename post.rooms to bedrooms

Revision ID: cf1fff287c69
Revises: b80874a439b4
Create Date: 2026-06-13 22:45:13.708104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf1fff287c69'
down_revision = 'b80874a439b4'
branch_labels = None
depends_on = None


def upgrade():
    # Rename in place (batch mode) to preserve existing data rather than
    # the autogenerated add+drop, which would discard the column's values.
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('rooms', new_column_name='bedrooms',
                              existing_type=sa.String(length=100), existing_nullable=False)


def downgrade():
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('bedrooms', new_column_name='rooms',
                              existing_type=sa.String(length=100), existing_nullable=False)
